from pathlib import Path
from lsprotocol import types


def initialize_params_example(root_dir: Path) -> types.InitializeParams:
    # Sample reconstructed from vscode initialize request
    return types.InitializeParams(
        capabilities=types.ClientCapabilities(
            workspace=types.WorkspaceClientCapabilities(
                apply_edit=True,
                workspace_edit=types.WorkspaceEditClientCapabilities(
                    document_changes=True,
                    resource_operations=(
                        types.ResourceOperationKind.Create,
                        types.ResourceOperationKind.Rename,
                        types.ResourceOperationKind.Delete,
                    ),
                    failure_handling=types.FailureHandlingKind.TextOnlyTransactional,
                    normalizes_line_endings=True,
                    change_annotation_support=types.ChangeAnnotationsSupportOptions(
                        groups_on_label=True
                    ),
                    metadata_support=None,
                    snippet_edit_support=None,
                ),
                did_change_configuration=types.DidChangeConfigurationClientCapabilities(
                    dynamic_registration=True
                ),
                did_change_watched_files=types.DidChangeWatchedFilesClientCapabilities(
                    dynamic_registration=True,
                    relative_pattern_support=True,
                ),
                symbol=types.WorkspaceSymbolClientCapabilities(
                    dynamic_registration=True,
                    symbol_kind=types.ClientSymbolKindOptions(
                        value_set=(
                            types.SymbolKind.File,
                            types.SymbolKind.Module,
                            types.SymbolKind.Namespace,
                            types.SymbolKind.Package,
                            types.SymbolKind.Class,
                            types.SymbolKind.Method,
                            types.SymbolKind.Property,
                            types.SymbolKind.Field,
                            types.SymbolKind.Constructor,
                            types.SymbolKind.Enum,
                            types.SymbolKind.Interface,
                            types.SymbolKind.Function,
                            types.SymbolKind.Variable,
                            types.SymbolKind.Constant,
                            types.SymbolKind.String,
                            types.SymbolKind.Number,
                            types.SymbolKind.Boolean,
                            types.SymbolKind.Array,
                            types.SymbolKind.Object,
                            types.SymbolKind.Key,
                            types.SymbolKind.Null,
                            types.SymbolKind.EnumMember,
                            types.SymbolKind.Struct,
                            types.SymbolKind.Event,
                            types.SymbolKind.Operator,
                            types.SymbolKind.TypeParameter,
                        )
                    ),
                    tag_support=types.ClientSymbolTagOptions(
                        value_set=(types.SymbolTag.Deprecated,)
                    ),
                    resolve_support=types.ClientSymbolResolveOptions(
                        properties=("location.range",)
                    ),
                ),
                execute_command=types.ExecuteCommandClientCapabilities(
                    dynamic_registration=True
                ),
                workspace_folders=True,
                configuration=True,
                semantic_tokens=types.SemanticTokensWorkspaceClientCapabilities(
                    refresh_support=True
                ),
                code_lens=types.CodeLensWorkspaceClientCapabilities(
                    refresh_support=True
                ),
                file_operations=types.FileOperationClientCapabilities(
                    dynamic_registration=True,
                    did_create=True,
                    will_create=True,
                    did_rename=True,
                    will_rename=True,
                    did_delete=True,
                    will_delete=True,
                ),
                inline_value=types.InlineValueWorkspaceClientCapabilities(
                    refresh_support=True
                ),
                inlay_hint=types.InlayHintWorkspaceClientCapabilities(
                    refresh_support=True
                ),
                diagnostics=types.DiagnosticWorkspaceClientCapabilities(
                    refresh_support=True
                ),
                folding_range=types.FoldingRangeWorkspaceClientCapabilities(
                    refresh_support=True
                ),
                text_document_content=None,
            ),
            text_document=types.TextDocumentClientCapabilities(
                synchronization=types.TextDocumentSyncClientCapabilities(
                    dynamic_registration=True,
                    will_save=True,
                    will_save_wait_until=True,
                    did_save=True,
                ),
                filters=None,
                completion=types.CompletionClientCapabilities(
                    dynamic_registration=True,
                    completion_item=types.ClientCompletionItemOptions(
                        snippet_support=True,
                        commit_characters_support=True,
                        documentation_format=(
                            types.MarkupKind.Markdown,
                            types.MarkupKind.PlainText,
                        ),
                        deprecated_support=True,
                        preselect_support=True,
                        tag_support=types.CompletionItemTagOptions(
                            value_set=(types.CompletionItemTag.Deprecated,)
                        ),
                        insert_replace_support=True,
                        resolve_support=types.ClientCompletionItemResolveOptions(
                            properties=(
                                "documentation",
                                "detail",
                                "additionalTextEdits",
                            )
                        ),
                        insert_text_mode_support=types.ClientCompletionItemInsertTextModeOptions(
                            value_set=(
                                types.InsertTextMode.AsIs,
                                types.InsertTextMode.AdjustIndentation,
                            )
                        ),
                        label_details_support=True,
                    ),
                    completion_item_kind=types.ClientCompletionItemOptionsKind(
                        value_set=(
                            1,
                            2,
                            3,
                            4,
                            5,
                            6,
                            7,
                            8,
                            9,
                            10,
                            11,
                            12,
                            13,
                            14,
                            15,
                            16,
                            17,
                            18,
                            19,
                            20,
                            21,
                            22,
                            23,
                            24,
                            25,
                        )
                    ),
                    insert_text_mode=types.InsertTextMode.AdjustIndentation,
                    context_support=True,
                    completion_list=types.CompletionListCapabilities(
                        item_defaults=(
                            "commitCharacters",
                            "editRange",
                            "insertTextFormat",
                            "insertTextMode",
                            "data",
                        ),
                        apply_kind_support=None,
                    ),
                ),
                hover=types.HoverClientCapabilities(
                    dynamic_registration=True,
                    content_format=(
                        types.MarkupKind.Markdown,
                        types.MarkupKind.PlainText,
                    ),
                ),
                signature_help=types.SignatureHelpClientCapabilities(
                    dynamic_registration=True,
                    signature_information=types.ClientSignatureInformationOptions(
                        documentation_format=(
                            types.MarkupKind.Markdown,
                            types.MarkupKind.PlainText,
                        ),
                        parameter_information=types.ClientSignatureParameterInformationOptions(
                            label_offset_support=True
                        ),
                        active_parameter_support=True,
                        no_active_parameter_support=None,
                    ),
                    context_support=True,
                ),
                declaration=types.DeclarationClientCapabilities(
                    dynamic_registration=True,
                    link_support=True,
                ),
                definition=types.DefinitionClientCapabilities(
                    dynamic_registration=True,
                    link_support=True,
                ),
                type_definition=types.TypeDefinitionClientCapabilities(
                    dynamic_registration=True,
                    link_support=True,
                ),
                implementation=types.ImplementationClientCapabilities(
                    dynamic_registration=True,
                    link_support=True,
                ),
                references=types.ReferenceClientCapabilities(dynamic_registration=True),
                document_highlight=types.DocumentHighlightClientCapabilities(
                    dynamic_registration=True
                ),
                document_symbol=types.DocumentSymbolClientCapabilities(
                    dynamic_registration=True,
                    symbol_kind=types.ClientSymbolKindOptions(
                        value_set=(
                            types.SymbolKind.File,
                            types.SymbolKind.Module,
                            types.SymbolKind.Namespace,
                            types.SymbolKind.Package,
                            types.SymbolKind.Class,
                            types.SymbolKind.Method,
                            types.SymbolKind.Property,
                            types.SymbolKind.Field,
                            types.SymbolKind.Constructor,
                            types.SymbolKind.Enum,
                            types.SymbolKind.Interface,
                            types.SymbolKind.Function,
                            types.SymbolKind.Variable,
                            types.SymbolKind.Constant,
                            types.SymbolKind.String,
                            types.SymbolKind.Number,
                            types.SymbolKind.Boolean,
                            types.SymbolKind.Array,
                            types.SymbolKind.Object,
                            types.SymbolKind.Key,
                            types.SymbolKind.Null,
                            types.SymbolKind.EnumMember,
                            types.SymbolKind.Struct,
                            types.SymbolKind.Event,
                            types.SymbolKind.Operator,
                            types.SymbolKind.TypeParameter,
                        )
                    ),
                    hierarchical_document_symbol_support=True,
                    tag_support=types.ClientSymbolTagOptions(
                        value_set=(types.SymbolTag.Deprecated,)
                    ),
                    label_support=True,
                ),
                code_action=types.CodeActionClientCapabilities(
                    dynamic_registration=True,
                    code_action_literal_support=types.ClientCodeActionLiteralOptions(
                        code_action_kind=types.ClientCodeActionKindOptions(
                            value_set=(
                                "",
                                "quickfix",
                                "refactor",
                                "refactor.extract",
                                "refactor.inline",
                                "refactor.rewrite",
                                "source",
                                "source.organizeImports",
                            )
                        )
                    ),
                    is_preferred_support=True,
                    disabled_support=True,
                    data_support=True,
                    resolve_support=types.ClientCodeActionResolveOptions(
                        properties=("edit",)
                    ),
                    honors_change_annotations=True,
                    documentation_support=None,
                    tag_support=None,
                ),
                code_lens=types.CodeLensClientCapabilities(
                    dynamic_registration=True,
                    resolve_support=None,
                ),
                document_link=types.DocumentLinkClientCapabilities(
                    dynamic_registration=True,
                    tooltip_support=True,
                ),
                color_provider=types.DocumentColorClientCapabilities(
                    dynamic_registration=True
                ),
                formatting=types.DocumentFormattingClientCapabilities(
                    dynamic_registration=True
                ),
                range_formatting=types.DocumentRangeFormattingClientCapabilities(
                    dynamic_registration=True,
                    ranges_support=True,
                ),
                on_type_formatting=types.DocumentOnTypeFormattingClientCapabilities(
                    dynamic_registration=True
                ),
                rename=types.RenameClientCapabilities(
                    dynamic_registration=True,
                    prepare_support=True,
                    prepare_support_default_behavior=types.PrepareSupportDefaultBehavior.Identifier,
                    honors_change_annotations=True,
                ),
                folding_range=types.FoldingRangeClientCapabilities(
                    dynamic_registration=True,
                    range_limit=5000,
                    line_folding_only=True,
                    folding_range_kind=types.ClientFoldingRangeKindOptions(
                        value_set=("comment", "imports", "region")
                    ),
                    folding_range=types.ClientFoldingRangeOptions(collapsed_text=False),
                ),
                selection_range=types.SelectionRangeClientCapabilities(
                    dynamic_registration=True
                ),
                publish_diagnostics=types.PublishDiagnosticsClientCapabilities(
                    version_support=False,
                    related_information=True,
                    tag_support=types.ClientDiagnosticsTagOptions(
                        value_set=(
                            types.DiagnosticTag.Unnecessary,
                            types.DiagnosticTag.Deprecated,
                        )
                    ),
                    code_description_support=True,
                    data_support=True,
                ),
                call_hierarchy=types.CallHierarchyClientCapabilities(
                    dynamic_registration=True
                ),
                semantic_tokens=types.SemanticTokensClientCapabilities(
                    requests=types.ClientSemanticTokensRequestOptions(
                        range=True,
                        full=types.ClientSemanticTokensRequestFullDelta(delta=True),
                    ),
                    token_types=(
                        "namespace",
                        "type",
                        "class",
                        "enum",
                        "interface",
                        "struct",
                        "typeParameter",
                        "parameter",
                        "variable",
                        "property",
                        "enumMember",
                        "event",
                        "function",
                        "method",
                        "macro",
                        "keyword",
                        "modifier",
                        "comment",
                        "string",
                        "number",
                        "regexp",
                        "operator",
                        "decorator",
                    ),
                    token_modifiers=(
                        "declaration",
                        "definition",
                        "readonly",
                        "static",
                        "deprecated",
                        "abstract",
                        "async",
                        "modification",
                        "documentation",
                        "defaultLibrary",
                    ),
                    formats=(types.TokenFormat.Relative,),
                    dynamic_registration=True,
                    overlapping_token_support=False,
                    multiline_token_support=False,
                    server_cancel_support=True,
                    augments_syntax_tokens=True,
                ),
                linked_editing_range=types.LinkedEditingRangeClientCapabilities(
                    dynamic_registration=True
                ),
                moniker=None,
                type_hierarchy=types.TypeHierarchyClientCapabilities(
                    dynamic_registration=True
                ),
                inline_value=types.InlineValueClientCapabilities(
                    dynamic_registration=True
                ),
                inlay_hint=types.InlayHintClientCapabilities(
                    dynamic_registration=True,
                    resolve_support=types.ClientInlayHintResolveOptions(
                        properties=(
                            "tooltip",
                            "textEdits",
                            "label.tooltip",
                            "label.location",
                            "label.command",
                        )
                    ),
                ),
                diagnostic=types.DiagnosticClientCapabilities(
                    dynamic_registration=True,
                    related_document_support=False,
                    related_information=None,
                    tag_support=None,
                    code_description_support=None,
                    data_support=None,
                ),
                inline_completion=types.InlineCompletionClientCapabilities(
                    dynamic_registration=True
                ),
            ),
            notebook_document=types.NotebookDocumentClientCapabilities(
                synchronization=types.NotebookDocumentSyncClientCapabilities(
                    dynamic_registration=True,
                    execution_summary_support=True,
                )
            ),
            window=types.WindowClientCapabilities(
                work_done_progress=True,
                show_message=types.ShowMessageRequestClientCapabilities(
                    message_action_item=types.ClientShowMessageActionItemOptions(
                        additional_properties_support=True
                    )
                ),
                show_document=types.ShowDocumentClientCapabilities(support=True),
            ),
            general=types.GeneralClientCapabilities(
                stale_request_support=types.StaleRequestSupportOptions(
                    cancel=True,
                    retry_on_content_modified=(
                        "textDocument/semanticTokens/full",
                        "textDocument/semanticTokens/range",
                        "textDocument/semanticTokens/full/delta",
                    ),
                ),
                regular_expressions=types.RegularExpressionsClientCapabilities(
                    engine="ECMAScript",
                    version="ES2020",
                ),
                markdown=types.MarkdownClientCapabilities(
                    parser="marked",
                    version="1.1.0",
                    allowed_tags=None,
                ),
                position_encodings=("utf-16",),
            ),
            experimental=None,
        ),
        process_id=None,  # This must be None. Otherwise backend server process ends immediately by misunderstanding the client process is already ended: detecting the 'actual' process id is not relevant.
        client_info=types.ClientInfo(
            name="Visual Studio Code",
            version="1.108.0",
        ),
        locale="en",
        root_path=str(root_dir.resolve()),
        root_uri=path_encode_colon(root_dir.resolve().as_uri()),
        # BasedPyright-specific initialization options to enable inlay hints for generic types
        initialization_options={
            "basedpyright": {
                "inlayHints": {
                    "genericTypes": True,
                }
            },
            "basedpyright.analysis": {
                "inlayHints": {
                    "genericTypes": True,
                }
            },
        },
        trace=types.TraceValue.Off,
        work_done_token=None,
        workspace_folders=(
            types.WorkspaceFolder(
                uri=path_encode_colon(root_dir.resolve().as_uri()),
                name="RunFileTest",
            ),
        ),
    )


def path_encode_colon(uri: str) -> str:
    uri_header_split = uri.split(":///")
    return uri_header_split[0] + ":///" + uri_header_split[1].replace(":", "%3A")
